name: Start EC2 Instance

on:
  push:
    branches:
      - main
      
permissions:
  id-token: write
  contents: read
  
env:
  AWS_REGION: ap-south-1

jobs:
  start_instance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Latest Source Code
        uses: actions/checkout@v3
		
      - name: Get AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-arn: "arn:aws:iam::829169262051:instance-profile/test"
          assume-role-policy: |
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Action": "sts:AssumeRole",
                  "Principal": {
                    "Service": "ec2.amazonaws.com"
                  },
                  "Effect": "Allow",
                  "Sid": ""
                }
              ]
            }
          aws-region: ${{ env.AWS_REGION }}

      - name: start EC2 instance
        run: aws ec2 start-instances --instance-ids i-03d42a3e35df8cb78
