name: Stop EC2 Instance

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-west-2

jobs:
  stop-instance:
    runs-on: ubuntu-latest

    steps:
    - name: Get AWS Credentials
      uses: aws-actions/get-aws-credentials@v1
      with:
        role-arn: "arn:aws:iam::998163017104:role/gha/gha-tableau"

    - name: Stop EC2 instance
      uses: aws-actions/amazon-ec2-instance-actions@v1
      with:
        instance-ids: i-049df61146f12
        region: ${{ env.AWS_REGION }}
        action: stop
