name: Using arn to stop EC2 instance


on: push


jobs:
  stop_instance:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Get AWS credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        ROLE_ARN: arn:aws:iam::829169262051:role/aws-service-role/support.amazonaws.com/AWSServiceRoleForSupport
        aws-region: ap-south-1
    - name: start EC2 instance
      run: aws ec2 stop-instances --instance-ids i-0d43d301d70a539d8
