name: AWS start ec2
on:
  push
env:
  AWS_REGION : "ap-south-1"   
permissions:
      id-token: write   
      contents: read    
jobs:
  Start_instance:
    runs-on: ubuntu-latest
    steps:

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::829169262051:role/github-oidc-role
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}

      - name: start EC2 instance
        run: aws ec2 start-instances --instance-ids i-03d42a3e35df8cb78
