name: Start EC2 Instance

on:
  push:
    branches:
      - main
permissions:
  id-token: write   
  contents: read
env:
  AWS_REGION: ap-south-1

jobs:
  stop-instance:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: "arn:aws:iam::829169262051:role/EC2_latest"
        aws-region: ${{ env.AWS_REGION }}
        role-session-tagging: true
        audience: sts.amazonaws.com

    - name: Stop EC2 instance
      run: |
        aws ec2 start-instances --instance-ids i-03d42a3e35df8cb78
