name: Stop EC2 Instance

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1

jobs:
  stop-instance:
    runs-on: ubuntu-latest

    steps:
    - name: Get AWS Credentials
      uses: aws-actions/get-aws-credentials@v1
      with:
        role-arn: "arn:aws:iam::829169262051:role/aws-service-role/support.amazonaws.com/AWSServiceRoleForSupport"

    - name: Stop EC2 instance
      uses: aws-actions/amazon-ec2-instance-actions@v1
      with:
        instance-ids: i-0d43d301d70a539d8
        region: ${{ env.AWS_REGION }}
        action: stop
