name: Stop EC2 Instance

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1

jobs:
  stop-instance:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: "arn:aws:iam::829169262051:role/aws-service-role/support.amazonaws.com/AWSServiceRoleForSupport"
        aws-region: ${{ env.AWS_REGION }}
        audience: sts.amazonaws.com

    - name: Stop EC2 instance
      run: |
        aws ec2 stop-instances --instance-ids i-0d43d301d70a539d8
