name: Launch EC2 Instance

on: [push]

jobs:
  launch_ec2_instance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up AWS creentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Launch EC2 Instance
        uses: aws-actions/ec2-launch-instance@v1
        with:
          region: ${{ secrets.AWS_REGION }}
          image-id: ${{ secrets.AWS_AMI_ID }}
          instance-type: t2.micro
          security-groups: default
          subnet-id: ${{ secrets.AWS_SUBNET_ID }}
          key-name: ${{ secrets.AWS_KEY_NAME }}
          tag-key: launch-by
          tag-value: GitHub-Actions
 
