name: AWS EC2 Instance

//on:
  push:
    branches:
      - main

jobs:
  launch-ec2-instance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Launch EC2 instance
      run: |
        aws ec2 run-instances \
          --image-id ami-0cca134ec43cf708f \
          --instance-type t2.micro \
          --key-name Launch_ec2 \
          --subnet-id subnet-051991db227ed4193 \
          --security-group-ids sg-04c1c785570f853a6 \
          --associate-public-ip-address
