name: AWS EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  launch-ec2-instance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Launch EC2 instance
      run: |
        aws ec2 run-instances \
          --image-id ami-0f948dba95c71c71c \
          --instance-type t2.micro \
          --key-name MyKeyPair \
          --subnet-id subnet-01234567890abcdef0 \
          --security-group-ids sg-01234567890abcdef0 \
          --associate-public-ip-address
