name: Stop EC2 instance

on:
  push:
    branches:
      - main

jobs:
  stop-instance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Stop EC2 instance
      env:
        AWS_REGION: ap-south-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        apt-get update
        apt-get install -y awscli
        aws ec2 stop-instances --instance-ids i-03d42a3e35df8cb78
