name: Stop EC2 instance

on:
  push:
    branches:
      -main
      
      
jobs:
  stop-instance:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v4
      with:
        node-version: 16
    - name: Install AWS SDK
      run: npm install aws-sdk
    - name: Stop EC2 Instance
      run: |
        const AWS = require('aws-sdk');
        const ec2 = new AWS.EC2({ region: 'ap-south-1' });
        const params = {
          InstanceIds: [ 'i-0d43d301d70a539d8' ]
        };
        ec2.stopInstances(params, (err, data) => {
          if (err) {
            console.log('Error', err);
          } else {
            console.log('Success', data);
          }
        });
